
raw_path: "data/raw"
processed_path: "data/processed"
embeddings_path: "data/embeddings"

ingestion:
  chunk_size: 500
  chunk_overlap: 50
  languages: ["pt", "en"]

embedder:
  model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  batch_size: 64
  normalize: true

vector_store:
  type: "faiss"
  index_factory: "Flat"
  metric: "L2"
  save_index_path: "data/embeddings/faiss_index.idx"

llm:
  provider: "openai"
  model_name: "gpt-3.5-turbo"
  max_tokens: 512
  temperature: 0.7
  top_p: 0.9
  api_key_env: "OPENAI_API_KEY"

api:
  host: "0.0.0.0"
  port: 8000
  docs_url: "/docs"

logging:
  level: "INFO"
  format: "[%(asctime)s] %(levelname)s %(name)s: %(message)s"

evaluation:
  top_k: 5
  benchmark_path: "tests/benchmark.json"
  save_reports: true
  reports_path: "reports/"